version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Set execute permission for gradlew
          command: chmod +x ./gradlew
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - run:
          name: Run tests
          command: ./gradlew test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
