version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  build-and-test:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Build project
          command: ./gradlew assembleDebug
      - run:
          name: Run unit tests
          command: ./gradlew testDebug
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: develop
