version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  build-and-test:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            java -version
      - run:
          name: Set execute permission for gradlew
          command: chmod +x ./gradlew
      - android/restore-gradle-cache
      - run:
          name: Build project
          command: ./gradlew assembleDebug
      - run:
          name: Run unit tests
          command: ./gradlew testDebug
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: develop
